### ISSUE TITLE
Transponder Selection Drop Down Continuously Cycles

### ISSUE THREAD

**Issue by c-ancell** [brills/SatHunter#1]
When viewing the satellite details screen, touch the transponder selection dropdown menu. The menu has a subtle flash. It appears it is continuously reloading. This makes it difficult to scroll to see additional options, like with ISS selected. Only those options initially shown are available.

iPhone 14 Pro Max
iOS 17.1.1

**Comment by brills** [comment]
Yep. I found the same when trying to work ISS.. I'll push a temporary fix soon.

**Comment by brills** [comment]
I uploaded the 1.0.3 which contains the fix, to app store. Wait a couple of days for it to be approved.
